# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: toml -*-

[project]
name = "yaml-language-server-feedstock"
version = "3.45.4"
description = "Pixi configuration for conda-forge/yaml-language-server-feedstock"
authors = ["@conda-forge/yaml-language-server"]
channels = ["conda-forge"]
platforms = ['linux-64', 'osx-64', 'win-64']

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
rattler-build = "*"

[tasks]
inspect-all = "inspect_artifacts --all-packages"
build = "rattler-build build --recipe recipe"
"build-linux_64_nodejs22" = "rattler-build build --recipe recipe -m .ci_support/linux_64_nodejs22.yaml"
"inspect-linux_64_nodejs22" = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_nodejs22.yaml"
"build-linux_64_nodejs20" = "rattler-build build --recipe recipe -m .ci_support/linux_64_nodejs20.yaml"
"inspect-linux_64_nodejs20" = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_nodejs20.yaml"

[feature.smithy.dependencies]
conda-smithy = "*"

[feature.smithy.tasks]
build-locally = "python ./build-locally.py"
smithy = "conda-smithy"
rerender = "conda-smithy rerender"
lint = "conda-smithy lint recipe"

[environments]
smithy = ["smithy"]